project_name         = "static-road-x"
gcp_credentials_path  = "/path/static-road-310823-8c830c80bbd6.json"
region               = "us-central1"
zone                 = "us-central1-a"
ssh_username         = "challengeuser"
ssh_pub_key_path     = "/path/.ssh/challengeuser.pub"
ssh_priv_key_path     = "/path/.ssh/challengeuser-trial"
